name: 'Chat with GPT'
description: 'Send a message to GPT using OpenAI API'
icon: 'message-circle'
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true
    secret: true
  message:
    description: 'Message to send to GPT'
    required: true
  temperature:
    description: 'Temperature for the GPT model'
    required: false
    default: 0.7
  model:
    description: 'GPT model to use'
    required: false
    default: 'gpt-4o'
runs:
  using: 'composite'
  steps:
    - name: Send message to GPT
      id: send_message
      shell: bash
      run: |
        response=$(curl -s -X POST \
        https://api.openai.com/v1/chat/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ inputs.openai_api_key }}" \
        -d '{
             "model": "${{ inputs.model }}",
             "messages": [{"role": "user", "content": "${{ inputs.message }}"}],
             "temperature": ${{ inputs.temperature }}
           }')

        echo "$response" | jq -r '.choices[0].message.content // .error.message'
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
