name: 'Chat with GPT'
description: 'Send a message to GPT and extract content'
author: 'Your Name'
inputs:
  api_key:
    description: 'API key for accessing OpenAI GPT'
    required: true
  message:
    description: 'Message to send to GPT'
    required: true
    default: 'Generate me a random 3 sentences text'
  temperature:
    description: 'Temperature setting for GPT'
    required: true
    default: '0.5'
  model:
    description: 'Model to use for GPT'
    required: true
    default: 'gpt-4o'
outputs:
  content:
    description: 'The content extracted from GPT response'
runs:
  using: 'composite'
  steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Send message to GPT and extract content
      run: |
        response=$(curl -X POST \
          https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_key }}" \
          -d '{
               "model": "${{ inputs.model }}",
               "messages": [{"role": "user", "content": "${{ inputs.message }}"}],
               "temperature": ${{ inputs.temperature }}
             }')
        echo "$response" | jq -r '.choices[0].message.content' > content.txt
        echo "::set-output name=content::$(cat content.txt)"