name: Chat with GPT

on: [push]

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use chat-with-gpt-action
      uses: ./  # This refers to the action in the same repository. Change it to your repository path when publishing.
      with:
        openai_api_key: ${{ secrets.OPENAI_KEY }}
        message: 'Say this is a test!'
        temperature: 0.7
        model: 'gpt-4o'