name: Chat with GPT

on: [push]

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use chat-with-gpt-action
      id: chat
      uses: BorislavStefanov31/chatgpt-action@v1.0.0
      with:
        openai_api_key: ${{ secrets.OPENAI_KEY }}
        message: 'Say this is a test!'
        temperature: 0.7
        model: 'gpt-4o'

    - name: Output GPT Response
      run: echo "${{ steps.chat.outputs.response }}"